### ISSUE TITLE
Webpacks packs up font files from materialize.css

### ISSUE THREAD

**Issue by Swendude** [Swendude/Tortoise#1]
Materialize.css is bundled by webpack in a way that includes all the [Roboto font types](https://fonts.google.com/specimen/Roboto) as .woff files in the ```/dist``` folder. It would be better to get those files from google fonts or a different CDN.

**Comment by jlengrand** [comment]
This seems relevant : https://github.com/Dogfalo/materialize/issues/4797, but I don't know in what way yet :D

**Comment by Swendude** [comment]
For now I see this as 'solved' by importing the fonts into dist/fonts. Fixed in 2c5b53a0c297760b165b4a2ee7a8018193489232.
